apiVersion: v1
kind: Namespace
metadata:
  name: cks-falco
---
apiVersion: v1
kind: Pod
metadata:
  name: falco-target
  namespace: cks-falco
  labels:
    app: falco-target
spec:
  containers:
    - name: toolbox
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: true
        capabilities:
          add: ["NET_RAW"]
