apiVersion: v1
kind: Namespace
metadata:
  name: cks-image
---
apiVersion: v1
kind: Pod
metadata:
  name: insecure-app
  namespace: cks-image
  labels:
    app: insecure-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: secure-app
  namespace: cks-image
  labels:
    app: secure-app
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:1.27-alpine
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: false
