apiVersion: v1
kind: Namespace
metadata:
  name: cks-rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: cks-rbac
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-read-only
  namespace: cks-rbac
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: cks-rbac
subjects:
  - kind: ServiceAccount
    name: pod-reader
    namespace: cks-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-read-only
